config/routes.rb
Minishopify::Application.routes.draw do

  resources :orders, only: ['new', 'create']
  get "/carts/:id", to: "carts#show", as: "cart"
  delete "/carts/:id", to: "carts#destroy"
  root "store#index"
  get "/store/products/:id", to: "store#show", as: "store"
  resources :products
  post "/line_items", to: "line_items#create"
  delete "/line_items/:id", to: "line_items#destroy", as: "line_item"
  put "/line_items/:id", to: "line_items#decrement"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)

		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end

		current_item
	end
	def total_price
      line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def decrement_or_destroy
    if quantity > 1
      decrement!(:quantity)
    else
      destroy
    end
  end
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      # set id to nil so that item doesn't go poof when we delete the cart
      item.cart_id = nil

      # rails knows that order has many line_items, so it adds these items to the line_items collection for this order.
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart

  def show
  end

  def destroy
  	@cart.destroy
  	session[:cart_id] = nil
  	redirect_to root_url, notice: "Cart emptied"
  end

  private
  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  def set_cart
    if session[:cart_id].nil?
        @cart = Cart.create
        session[:cart_id] = @cart.id
    else
        @cart = Cart.find(session[:cart_id])
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  before_action :set_line_item, except: ['create']

  def create
    product = Product.find(params[:product])
    @line_item = @cart.add_product(product.id)
    @line_item.save

    redirect_to cart_path(@cart)
  end

  def destroy
    @line_item.destroy

    redirect_to cart_path(@cart), notice: 'Line item removed'
  end

  def decrement
    @line_item.decrement_or_destroy
    redirect_to cart_path(@cart), notice: 'Line item removed'
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  include CurrentCart
  before_action :set_cart

  def new
    if @cart.line_items.empty?
      redirect_to root_url, notice: 'Your cart is empty'
    end
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    @order.save

    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil

    OrderNotifier.received(@order).deliver
    redirect_to root_url, notice: 'Thank you for your order!'
  end

  private
  def order_params
    params.require(:order).permit(:name, :address, :email, :pay_type)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def show
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to product_path(@product)
		else
			render nothing: true
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			redirect_to product_path(@product)
		else
			render nothing: true
		end
	end

	def destroy
		@product.destroy
		redirect_to products_path
	end

	private

	def set_product
		@product = Product.find_by_id(params[:id])
	end

	def product_params
		params.require(:product).permit(:title, :description, :image_url, :price)
	end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<%= render cart.line_items %>

app/views/carts/show.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>

<h1>Cart</h1>
<table class="table">
<%= render @cart %>
    <tr class="total_line">
      <td> </td>
      <td colspan="2">Total</td>
      <td class="total-price"><%= number_to_currency(@cart.total_price) %></td>
    </tr>

</table>
<%= link_to raw('<i class="icon-arrow-left"></i> Back to Catalog'), root_path, class: "btn btn-small btn-primary"  %>
<%= link_to raw('<i class="icon-remove"></i> Empty'), @cart, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-small btn-danger" %>
<%= link_to raw('<i class="icon-ok"></i> Checkout'), new_order_path, class: "btn btn-small btn-success"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minishopify</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="leaves-ui">
  <h1 class="artcart"><%= image_tag('theArtCart2.png')%></h1>
</div>
<div class="container">
  <div class="row">
<%= yield %>
  </div>
 </div>
</body>
</html>

app/views/line_items/_line_item.html.erb
<tr>
  <td>  <%= image_tag("small"+line_item.product.image_url, class: 'img-polaroid') %></td>
<td> <span class='large-type'><%= line_item.quantity %></span> x </td>
<td><%= line_item.product.title %></td>

<td class="price"><%= number_to_currency(line_item.total_price) %></td>
<td> <%= link_to raw('<i class="icon-remove"></i> Remove All'), line_item, method: :delete, class: "btn btn-small btn-danger" %>
<%= link_to raw('<i class="icon-remove"></i> Remove One'), line_item, method: :put, class: "btn btn-small" %></p></td>

 </tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", line_item.quantity,
              truncate(line_item.product.title, length: 50)) %>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from Minishopify.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

app/views/orders/new.html.erb
<%= form_for(@order) do |f| %>
<div>
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div>
<%= f.label :email %>
<%= f.text_field :email %>
</div>
<div>
<%= f.label :address %>
<%= f.text_area :address %>
</div>
<div>
<%= f.label :pay_type %>
<%= f.text_field :pay_type %>
</div>
<%= f.submit %>
<% end %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table table-striped">
  <tr>
    <th> </th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Controls</th>
  </tr>

  <% @products.each do |product| %>
    <tr class="entry">
      <td>
          <%= image_tag(product.image_url, class: 'img-polaroid') %>
      </td>
      <td><%= product.title %></td>
      <td><%= product.description %></td>
      <td class="price"><%= number_to_currency(product.price) %></td>
      <td>
        <div class="displace">
        <%= link_to raw('<i class="icon-search"></i> Show'), product_path(product), class: "btn btn-small" %><br/>
        <%= link_to raw('<i class="icon-edit"></i> Edit'), edit_product_path(product), class: "btn btn-small" %><br/>
        <%= link_to raw('<i class="icon-remove"></i> Delete'), product, method: :delete,
          data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
        </div>
      </td>
    </tr>

  <% end %>
</table>

<%= link_to "Add Product", new_product_path %>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %></h1>

<ul>
  <li><%= @product.description %></li>
  <li><%= @product.image_url %></li>
  <li class="price"><%= number_to_currency(@product.price) %></li>
</ul>

<%= link_to raw('<i class="icon-edit"></i> Edit'), edit_product_path(@product),class: "btn btn-small" %><br/>

app/views/store/index.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>

<h1>Products Catalog</h1>



  <% @products.each do |product| %>
      <div class="row product_<%= product.id %>">
      <div class="span3">
        <%= link_to image_tag(product.image_url, class: 'img-polaroid'),
        store_path(product) %>
      </div>
    <div class="span6 descrip">
      <h3><%= product.title %></h3>
      <%= product.description %>
      <div>
          <span class="span1 price"><%= number_to_currency(product.price) %></span>
          <div class = "span1">
            <%= button_to 'Add to Cart', line_items_path(product: product.id), class: "btn btn-small btn-nomarg-down"%>
            <%= link_to raw('<i class="icon-search"></i> Show'), store_path(product), class: "btn btn-small btn-nomarg" %><br/>

              </div>
        </div>
      </div>
    </div>

  <% end %>

app/views/store/show.html.erb
<h1 class="title"><%= @product.title %></h1>
<div class="label-center">
<%= image_tag("large"+@product.image_url, class: 'img-polaroid') %>
  <div class="caption">
  <p> <%= @product.description %></p>
  <p class="price"><%= number_to_currency(@product.price) %></p>
</div>
</div>
</ul>